### PR TITLE
Multiple asset directories with same public cache

### PR DESCRIPTION
**Pull request by fduarte42**

### CODE REVIEW

**Comment by rodmcnew** [comment]
Hi @fduarte42 . It is hard for us to test changes for Expressive 3 because we aren't using Expressive 3 and don't plan to use it in the future (moving to nodeJS). I think the best thing may be for you to just fork this project and we can add a link to your fork saying yours is the more well-supported version for Expressive 3. If you do this, leave a comment here and I'll add a note with a link to your project on this project's readme file.

**Comment by fduarte42** [comment]
I can take it over. I've never taken over a Project on Github. How would the procedure be?

**Comment by rodmcnew** [comment]
Hi Tito. It wouldn't really be a "take over" of the  "reliv/serve-static" packagist namespace. We cannot allow non-reliv-employees to take over "reliv/" namespaces on packagist or github. If you want to do it, It would be more like this:
1) You fork or re-upload the code to your own github repo
2) On packagist.org, you tell packagist about your new package under some other name than "reliv/serve-static"
3) Tell me what your new packagist package name is and i'll put a note on top of the "reliv/serve-static" readme saying something like "We don't support expressive 3, for expressive 3 support checkout Tito's project at (whatever link)"

**Comment by fduarte42** [comment]
Hi,
I've created a fork at https://github.com/fduarte42/zend-expressive-static-files
Is it ok that I changed the namespace? And should I keep the License?

**Comment by rodmcnew** [comment]
Hi Tito,

I made a link to your project in the Reliv project's readme. 

You have Reliv International's permission to re-license your fork of this project however you want. I'd suggest using the ISC license copy-righted to yourself, but feel free to do whatever you want.

Yes changing the namespace to something not "reliv" is probably a good idea to avoid confusion.

**Pull request closed without merging**
